spring.application.name=Gymfocus
spring.datasource.url=jdbc:postgresql://localhost:5432/Calculadorabasal
spring.datasource.username=postgres
spring.datasource.password=1204
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true